server:
  port: 3344

spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZHSYQ/microservicecloud-config.git #Github上面的git仓库
          
          
          
         # git@github.com:ZHSYQ/microservicecloud-config.git