server:
  port: 80
eureka:
  client:   #将客户端注册进入eureka的客户端
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
    register-with-eureka: false
feign:
  hystrix: 
    enabled: true